version: '3.9'
services:
    front-end:
        build: ./front-end
        ports:
            - '3000:3000'
        depends_on:
            - back-end
        volumes:
            - ./front-end/src/:/usr/src/app/src 
    back-end:
        build: ./back-end
        ports:
            - '4000:4000'
        depends_on:
            - mongo
        env_file:
            - ./back-end/.env
        environment:
            - API_KEY_TRAKT=${API_KEY_TRAKT}
            - API_KEY_TMDB=${API_KEY_TMDB}
            - TOKEN_SECRET=${TOKEN_SECRET}
        volumes:
            - ./back-end/src/:/usr/src/app/src
    mongo:
        image: mongo
        ports: 
            - '27017:27017'
        env_file:
            - ./back-end/.env
        environment:
            - MONGODB_USERNAME=${MONGODB_USERNAME}
            - MONGODB_PASSWORD=${MONGODB_PASSWORD}
 
